title: Jack Skidmore
description: Essays, prayers, and projects from Jack Skidmore.
baseurl: ""
url: "https://jackskidmore.co"
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: pretty
exclude:
  - README.md
